CREATE TABLE IF NOT EXISTS `#__flowcart_zones` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`active` TINYINT(1) NOT NULL DEFAULT '1',
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `#__flowcart_countries` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL,
	`iso_code` VARCHAR(3) NOT NULL,
	`has_states` TINYINT(1) NOT NULL DEFAULT '0',
	`needs_id_number` TINYINT(1) NOT NULL DEFAULT '0',
	`needs_zip_code` TINYINT(1) NOT NULL DEFAULT '1',
	`zip_code_format` VARCHAR(24) NOT NULL,
	`active` TINYINT(1) NOT NULL DEFAULT '1',
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `#__flowcart_states` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL,
	`iso_code` VARCHAR(7) NOT NULL,
	`country_id` INT(10) NOT NULL,
	`zone_id` INT(10) NOT NULL,
	`active` VARCHAR(7) NOT NULL,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;
